### ISSUE TITLE
Como baralhos representar a agenda?

### ISSUE THREAD

**Issue by sdsPedro** [fernandomorato/Saudepp#4]

**Comment by fernandomorato** [comment]
Os pacientes vão agendar as consultas e com o conjunto dos agendamentos de todos os pacientes, a gente monta a agenda. Ela pode ser representada com alguma estrutura de dados que tenha o paciente que será/está sendo atendido e os horários iniciais e finais da consulta. Só é disponível agendamentos entre os horários de abertura e fechamento da clínica.

**Comment by sdsPedro** [comment]
Ver agenda:
seleciona data OU médico OU paciente correspondente à consulta
mostrar lista de consultas em tabela que obedecem os filtros
